//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWithPenguin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Question
    {
        public int Question_Topic { get; set; }
        public int Question_ID { get; set; }
    
        public virtual Quiz_Within Quiz_Within { get; set; }
    }
}
