//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWithPenguin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Quizz_LearnWithPenguineEntities : DbContext
    {
        public Quizz_LearnWithPenguineEntities()
            : base("name=Quizz_LearnWithPenguineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Quiz_Within> Quiz_Within { get; set; }
        public virtual DbSet<Quiz_Question> Quiz_Question { get; set; }
    }
}
